### ISSUE TITLE
Errno::ENOENT: No such file or directory - Y:/etc/resolv.conf

### ISSUE THREAD

**Issue by perlun** [celluloid/celluloid-io#64]
It seems like the Celluloid::IO DNS resolver is a bit Unix-only for the moment. This is what I get when trying to run it on JRuby for Windows (when using it with a DNS host name; specifying an IP address works correctly).

```
Errno::ENOENT: No such file or directory - Y:/etc/resolv.conf
        org/jruby/RubyFile.java:333:in `initialize'
        org/jruby/RubyIO.java:1179:in `open'
        org/jruby/RubyKernel.java:333:in `open'
        org/jruby/RubyIO.java:3611:in `read'
        org/jruby/RubyIO.java:3708:in `read'
        Y:/Work/Source/hg/eCraft.appFactory-2013.6/src/server/gems/jruby/1.9/gems/celluloid-io-0.14.0/lib/celluloid/io/dns_resolver.rb:19:in `nameservers'
        Y:/Work/Source/hg/eCraft.appFactory-2013.6/src/server/gems/jruby/1.9/gems/celluloid-io-0.14.0/lib/celluloid/io/dns_resolver.rb:36:in `initialize'
        Y:/Work/Source/hg/eCraft.appFactory-2013.6/src/server/gems/jruby/1.9/gems/celluloid-io-0.14.0/lib/celluloid/io/tcp_socket.rb:66:in `initialize'
        Y:/Work/Source/hg/eCraft.appFactory-2013.6/src/server/gems/jruby/1.9/gems/celluloid-websocket-client-0.0.1/lib/celluloid/websocket/client/connection.rb:
14:in `initialize'
```

**Comment by digitalextremist** [comment]
How are we doing with this, since 11/13?

**Comment by perlun** [comment]
Age old, closing.
